<?php

return [
    'system_name' => 'The Local Youth Development Office of Nabua',
    'system_short' => 'LYDO',
    'republic' => 'Republic of the Philippines',
    'province' => 'Province of Camarines Sur',
    'lgu' => 'Municipality of Nabua',
    'agency' => 'Local Youth Development Office of Nabua',
    'agency_short' => 'LYDO',
    'office_description' => 'Local Youth Development Office — Municipality of Nabua',
    'address' => 'Nabua Local Government Center, Poblacion, Nabua, Camarines Sur',
    'phone' => '(054) 473-2100',
    'email' => 'mswdo@nabua.gov.ph',
    'hotline' => '8888',
    'office_hours' => 'Monday to Friday, 8:00 AM – 5:00 PM',
    'application_prefix' => 'CAMS',
    'applicant_prefix' => 'BEN',
    'release_prefix' => 'REL',

    'barangays' => [
        'Angustia',
        'Antipolo Old',
        'Antipolo Young',
        'Aro-aldao',
        'Bustrac',
        'Dolorosa',
        'Duran',
        'Inapatan',
        'La Opinion',
        'La Purisima',
        'Lourdes Old',
        'Lourdes Young',
        'Malawag',
        'Paloyon Oriental',
        'Paloyon Proper',
        'Salvacion Que Gatos',
        'San Antonio',
        'San Antonio Ogbon',
        'San Esteban',
        'San Francisco',
        'San Isidro',
        'San Isidro Inapatan',
        'San Jose',
        'San Juan',
        'San Luis',
        'San Miguel',
        'San Nicolas',
        'San Roque',
        'San Roque Madawon',
        'San Roque Sagumay',
        'San Vicente Gorong-Gorong',
        'San Vicente Ogbon',
        'Santa Barbara',
        'Santa Cruz',
        'Santa Elena Baras',
        'Santa Lucia Baras',
        'Santiago Old',
        'Santiago Young',
        'Santo Domingo',
        'Tandaay',
        'Topas Proper',
        'Topas Sogod',
    ],

    'release_methods' => [
        'cash' => 'Cash',
        'bank_transfer' => 'Bank Transfer',
        'ewallet' => 'E-Wallet',
        'check' => 'Check',
        'other' => 'Other authorized method',
    ],

    'sexes' => [
        'male' => 'Male',
        'female' => 'Female',
    ],

    'pwd_types' => [
        'visual' => 'Visual disability',
        'hearing' => 'Hearing disability',
        'speech' => 'Speech impairment',
        'orthopedic' => 'Orthopedic / physical disability',
        'intellectual' => 'Intellectual / mental disability',
        'psychosocial' => 'Psychosocial disability',
        'learning' => 'Learning disability',
        'chronic_illness' => 'Disability due to chronic illness',
        'multiple' => 'Multiple disabilities',
        'other' => 'Other',
    ],
];
